# Generated by Django 5.2.8 on 2025-11-26 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Опис')),
                ('status', models.CharField(choices=[('NEW', 'Нова'), ('IN_PROGRESS', 'В роботі'), ('REVIEW', 'Перевірка коду'), ('TESTING', 'Тестування'), ('DONE', 'Виконано'), ('CLOSED', 'Закрито')], default='NEW', max_length=20, verbose_name='Статус')),
                ('priority', models.CharField(choices=[('LOW', 'Низький'), ('MEDIUM', 'Середній'), ('HIGH', 'Високий'), ('CRITICAL', 'Критичний')], default='MEDIUM', max_length=20, verbose_name='Пріоритет')),
                ('story_points', models.PositiveSmallIntegerField(choices=[(1, '1 SP'), (2, '2 SP'), (3, '3 SP'), (5, '5 SP'), (8, '8 SP'), (13, '13 SP'), (21, '21 SP')], default=1, verbose_name='Оцінка складності (SP)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачі',
            },
        ),
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Суть помилки')),
                ('description', models.TextField(verbose_name='Детальний опис (Steps to reproduce)')),
                ('status', models.CharField(choices=[('NEW', 'Новий'), ('CONFIRMED', 'Підтверджено'), ('IN_PROGRESS', 'В роботі'), ('FIXED', 'Виправлено'), ('CLOSED', 'Закрито')], default='NEW', max_length=20, verbose_name='Статус')),
                ('priority', models.CharField(choices=[('LOW', 'Низький'), ('MEDIUM', 'Середній'), ('HIGH', 'Високий'), ('CRITICAL', 'Критичний')], default='MEDIUM', max_length=20, verbose_name='Пріоритет')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Виправлено')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugs', to='projects.project', verbose_name='Проєкт')),
            ],
            options={
                'verbose_name': 'Звіт про помилку',
                'verbose_name_plural': 'Звіти про помилки',
                'ordering': ['-created_at'],
            },
        ),
    ]
