# Generated by Django 5.2.8 on 2025-11-26 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва спринта')),
                ('goal', models.TextField(blank=True, verbose_name='Ціль спринта')),
                ('start_date', models.DateField(verbose_name='Початок')),
                ('end_date', models.DateField(verbose_name='Кінець')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активний')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='projects.project', verbose_name='Проєкт')),
            ],
            options={
                'verbose_name': 'Спринт',
                'verbose_name_plural': 'Спринти',
                'ordering': ['-start_date'],
            },
        ),
    ]
